export const prologoContent = [
  "Este no es un libro cualquiera.",
  "Es una obra colectiva. Viva.",
  "Un grito escrito por muchas manos, muchas conciencias, muchas almas que no han querido ser cómplices del silencio.",
  "Este libro no es solo un relato.",
  "Es un testimonio.",
  "Es un deber.",
  "Es una promesa a quienes vendrán después de nosotros: nuestros hijos, nuestros nietos, nuestros pueblos.",
  "No quiero que este libro se lea como una novela más.",
  "Quiero que sea un documento vivo, crudo, sincero, de lo que hemos vivido.",
  "No desde los medios.",
  "No desde las voces del poder.",
  "Sino desde la piel, desde la conciencia, desde la dignidad de quienes, sin ser palestinos, se han sentido parte de esta lucha.",
  "Porque este libro no está escrito por las víctimas directas del genocidio, ni por refugiados que han perdido sus hogares, ni siquiera necesariamente por quienes han pisado Gaza o Cisjordania.",
  "Este libro está escrito por personas de todo el mundo:",
  "personas que se han movilizado, que han alzado la voz, que han marchado, que han financiado, que han educado, que han acompañado al pueblo palestino desde sus propias realidades.",
  "Musulmanes, cristianos, ateos, agnósticos, laicos.",
  "Personas de todas las razas, ideologías, géneros y lenguas.",
  "Gente sencilla, pero con un compromiso inmenso.",
  "Gente que no podía seguir mirando hacia otro lado.",
  "",
  "Lo único que los une es una misma certeza:",
  "la causa palestina es la causa más noble de nuestra era.",
  "Este libro no lo han escrito expertos, ni políticos, ni instituciones.",
  "Lo han escrito personas.",
  "Personas que han actuado, que han alzado la voz, que han sostenido, que han llorado.",
  "Personas que no han estado allí, tal vez,",
  "pero que no han podido permanecer indiferentes.",
  "Y que han elegido contar, sentir y no olvidar.",
  "Porque lo que ha ocurrido —lo que ocurre hoy y seguirá ocurriendo si no lo detenemos— está siendo contado por el mismo verdugo.",
  "Por quienes masacran, por quienes oprimen, por quienes se esconden detrás de palabras grandes y discursos vacíos para justificar el asesinato de un pueblo.",
  "No queremos que le pase a Palestina lo que ya les ocurrió a tantos pueblos antes.",
  "Como les pasó a los pueblos indígenas de América.",
  "Sus historias, su resistencia, su sabiduría… todo ha sido contado desde la mirada del conquistador, del genocida, del invasor.",
  "Y hoy, siglos después, seguimos conociendo su historia a través de quienes los exterminaron.",
  "Eso no puede volver a pasar.",
  "Este libro nace precisamente para evitarlo.",
  "Nace para ser un documento vivo.",
  "Un refugio de verdad.",
  "Un testigo de lo que fue.",
  "Para que mañana, cuando muchos lo nieguen, lo disfracen, lo reinventen,",
  "haya al menos una voz —entre muchas otras voces que merecen ser escuchadas— que diga:",
  "nosotros no fuimos palestinos, pero no fuimos indiferentes.",
  "Nosotros vimos, sentimos y actuamos.",
  "Este libro no pretende hablar por todos.",
  "Cada persona tiene su historia, su herida, su manera de ver y sentir.",
  "Incluso entre quienes estamos del mismo lado, no hay una sola versión.",
  "Pero lo que sí nos une es el amor inmenso por la causa palestina,",
  "el rechazo a la injusticia",
  "y la certeza de que guardar silencio sería traicionar todo aquello en lo que creemos.",
  "Aquí comienza este camino.",
  "Un camino que no tiene fin.",
  "Porque este es un libro colectivo, pero también es un libro vivo.",
  "Un libro que no se cerrará mientras Palestina siga sufriendo.",
  "Un libro que no acabará hasta que Palestina vuelva a ser lo que fue,",
  "desde el río hasta el mar.",
  "Hasta que los palestinos recuperen su tierra, su dignidad, su libertad.",
  "Mientras haya causa, este libro seguirá vivo.",
  "Cada testimonio que aquí se recoge es un latido.",
  "Cada palabra, un impulso.",
  "Latidos de esperanza no es solo un libro.",
  "Es el latido de las almas puras de esta humanidad.",
  "Cada acto narrado, una sacudida del corazón colectivo.",
  "Cada palabra escrita, una pequeña llama que no quiere apagarse.",
  "El corazón es Gaza.",
  "Y mientras Gaza siga latiendo, la humanidad no estará perdida.",
  "Pero si ese corazón se detiene…",
  "habremos dejado de ser libres.",
  "Habremos dejado de ser humanos.",
  "Este libro es un latido vivo.",
  "Y seguirá latiendo mientras haya una causa por la que luchar,",
  "mientras haya una injusticia que denunciar,",
  "mientras quede alguien que no quiera callar.",
  "“Porque los grandes cambios no siempre nacen de gobiernos, ni de discursos, ni de organizaciones poderosas.",
  "A veces, las hazañas más significativas brotan de pequeños actos,",
  "realizados en silencio,",
  "desde la soledad,",
  "desde la escasez,",
  "desde la incertidumbre.",
  "Actos sencillos.",
  "Hechos por personas comunes.",
  "Sin certezas, sin garantías, sin saber si servirán de algo o si simplemente se perderán en el vacío.",
  "Pero aun así, se hacen.",
  "Porque nacen de la conciencia,",
  "de la dignidad,",
  "de la necesidad de no ser cómplice.",
  "Y son esos actos —mínimos, anónimos, solitarios—",
  "los que sostienen la esperanza",
  "y construyen el cambio real.”",
  "— Abdellah Yahyaoui Azuz —",
];
